# Generated by Django 4.0.2 on 2022-03-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_listings_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlists',
            field=models.ManyToManyField(blank=True, related_name='watchlists', to='auctions.Listing'),
        ),
    ]
