# Generated by Django 4.0.2 on 2022-03-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_user_watchlist_user_watchlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
            preserve_default=False,
        ),
    ]
