# Generated by Django 4.0.2 on 2022-04-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
